### PR TITLE
Update Foreman test branches in CI

### PR DESCRIPTION
**Pull request by nadjaheitmann**

### CODE REVIEW

**Review by maximiliankolb — APPROVED** [review]
diff LGTM; please merge with green GHA.

**Comment by nadjaheitmann** [comment]
Pipeline works for the newly added branches. Should we merge and fix delevop in a follow-up PR?

**Comment by maximiliankolb** [comment]
@nadjaheitmann I suggest to drop develop if it does not work. Then, you can create a follow-up issue/PR to add develop to the matrix and fix the tests.

**Comment by nadjaheitmann** [comment]
I would not drop it as it is a reminder that we need to adapt the plugin such that it would work with the development branch

**Comment by m-bucher** [comment]
IMHO we can leave `develop` build in. It is visible, which tests fail and we do plan to fix tests against `develop` anyway. So no need to temporarily drop them.

**Pull request merged**
